modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "ccgraphics"
version = "${version}"
displayName = "CC: Graphics"
authors = "sashafiesta"
description = "CraftOS-PC compatible graphics mode for CC:Tweaked terminals"

[[dependencies.ccgraphics]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ccgraphics]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ccgraphics]]
modId = "computercraft"
type = "required"
versionRange = "[1.117.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ccgraphics.mixins.json"

[[mixins]]
config = "ccgraphics-client.mixins.json"
